//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.03.07 at 11:56:42 PM EST 
//


package epcglobal.tdt.xsd._1;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Level complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Level">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="option" type="{urn:epcglobal:tdt:xsd:1}Option" maxOccurs="unbounded"/>
 *         &lt;element name="rule" type="{urn:epcglobal:tdt:xsd:1}Rule" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="type" use="required" type="{urn:epcglobal:tdt:xsd:1}LevelTypeList" />
 *       &lt;attribute name="prefixMatch" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="requiredParsingParameters" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="requiredFormattingParameters" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Level", propOrder = {
    "option",
    "rule"
})
public class Level {

    @XmlElement(required = true)
    protected List<Option> option;
    protected List<Rule> rule;
    @XmlAttribute(required = true)
    protected LevelTypeList type;
    @XmlAttribute
    protected String prefixMatch;
    @XmlAttribute
    protected String requiredParsingParameters;
    @XmlAttribute
    protected String requiredFormattingParameters;

    /**
     * Gets the value of the option property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the option property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOption().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Option }
     * 
     * 
     */
    public List<Option> getOption() {
        if (option == null) {
            option = new ArrayList<Option>();
        }
        return this.option;
    }

    /**
     * Gets the value of the rule property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the rule property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRule().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Rule }
     * 
     * 
     */
    public List<Rule> getRule() {
        if (rule == null) {
            rule = new ArrayList<Rule>();
        }
        return this.rule;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link LevelTypeList }
     *     
     */
    public LevelTypeList getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link LevelTypeList }
     *     
     */
    public void setType(LevelTypeList value) {
        this.type = value;
    }

    /**
     * Gets the value of the prefixMatch property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrefixMatch() {
        return prefixMatch;
    }

    /**
     * Sets the value of the prefixMatch property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrefixMatch(String value) {
        this.prefixMatch = value;
    }

    /**
     * Gets the value of the requiredParsingParameters property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRequiredParsingParameters() {
        return requiredParsingParameters;
    }

    /**
     * Sets the value of the requiredParsingParameters property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRequiredParsingParameters(String value) {
        this.requiredParsingParameters = value;
    }

    /**
     * Gets the value of the requiredFormattingParameters property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRequiredFormattingParameters() {
        return requiredFormattingParameters;
    }

    /**
     * Sets the value of the requiredFormattingParameters property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRequiredFormattingParameters(String value) {
        this.requiredFormattingParameters = value;
    }

}
