//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.03.07 at 11:56:42 PM EST 
//


package epcglobal.tdt.xsd._1;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for LevelTypeList.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="LevelTypeList">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="BINARY"/>
 *     &lt;enumeration value="TAG_ENCODING"/>
 *     &lt;enumeration value="PURE_IDENTITY"/>
 *     &lt;enumeration value="LEGACY"/>
 *     &lt;enumeration value="ONS_HOSTNAME"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "LevelTypeList")
@XmlEnum
public enum LevelTypeList {

    BINARY,
    TAG_ENCODING,
    PURE_IDENTITY,
    LEGACY,
    ONS_HOSTNAME;

    public String value() {
        return name();
    }

    public static LevelTypeList fromValue(String v) {
        return valueOf(v);
    }

}
