//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.03.07 at 11:56:42 PM EST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "urn:epcglobal:tdt:xsd:1")
package epcglobal.tdt.xsd._1;
