//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.03.07 at 11:56:42 PM EST 
//


package epcglobal.tdt.xsd._1;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Scheme complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Scheme">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="level" type="{urn:epcglobal:tdt:xsd:1}Level" maxOccurs="5" minOccurs="4"/>
 *       &lt;/sequence>
 *       &lt;attribute name="name" use="required" type="{urn:epcglobal:tdt:xsd:1}SchemeNameList" />
 *       &lt;attribute name="optionKey" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="tagLength" use="required" type="{urn:epcglobal:tdt:xsd:1}TagLengthList" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Scheme", propOrder = {
    "level"
})
public class Scheme {

    @XmlElement(required = true)
    protected List<Level> level;
    @XmlAttribute(required = true)
    protected SchemeNameList name;
    @XmlAttribute(required = true)
    protected String optionKey;
    @XmlAttribute(required = true)
    protected String tagLength;

    /**
     * Gets the value of the level property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the level property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLevel().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Level }
     * 
     * 
     */
    public List<Level> getLevel() {
        if (level == null) {
            level = new ArrayList<Level>();
        }
        return this.level;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link SchemeNameList }
     *     
     */
    public SchemeNameList getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link SchemeNameList }
     *     
     */
    public void setName(SchemeNameList value) {
        this.name = value;
    }

    /**
     * Gets the value of the optionKey property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOptionKey() {
        return optionKey;
    }

    /**
     * Sets the value of the optionKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOptionKey(String value) {
        this.optionKey = value;
    }

    /**
     * Gets the value of the tagLength property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTagLength() {
        return tagLength;
    }

    /**
     * Sets the value of the tagLength property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTagLength(String value) {
        this.tagLength = value;
    }

}
