//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.03.10 at 10:55:55 AM EDT 
//


package org.epcglobalinc;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Field complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Field">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="seq" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="bitLength" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="characterSet" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="compaction" type="{urn:epcglobal:tdt:xsd:1}CompactionMethodList" />
 *       &lt;attribute name="compression" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="padChar" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="padDir" type="{urn:epcglobal:tdt:xsd:1}PadDirectionList" />
 *       &lt;attribute name="decimalMinimum" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="decimalMaximum" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="length" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Field")
public class Field {

    @XmlAttribute(required = true)
    protected BigInteger seq;
    @XmlAttribute(required = true)
    protected String name;
    @XmlAttribute
    protected BigInteger bitLength;
    @XmlAttribute(required = true)
    protected String characterSet;
    @XmlAttribute
    protected String compaction;
    @XmlAttribute
    protected String compression;
    @XmlAttribute
    protected String padChar;
    @XmlAttribute
    protected PadDirectionList padDir;
    @XmlAttribute
    protected String decimalMinimum;
    @XmlAttribute
    protected String decimalMaximum;
    @XmlAttribute
    protected BigInteger length;

    /**
     * Gets the value of the seq property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSeq() {
        return seq;
    }

    /**
     * Sets the value of the seq property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSeq(BigInteger value) {
        this.seq = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the bitLength property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getBitLength() {
        return bitLength;
    }

    /**
     * Sets the value of the bitLength property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setBitLength(BigInteger value) {
        this.bitLength = value;
    }

    /**
     * Gets the value of the characterSet property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCharacterSet() {
        return characterSet;
    }

    /**
     * Sets the value of the characterSet property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCharacterSet(String value) {
        this.characterSet = value;
    }

    /**
     * Gets the value of the compaction property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCompaction() {
        return compaction;
    }

    /**
     * Sets the value of the compaction property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCompaction(String value) {
        this.compaction = value;
    }

    /**
     * Gets the value of the compression property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCompression() {
        return compression;
    }

    /**
     * Sets the value of the compression property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCompression(String value) {
        this.compression = value;
    }

    /**
     * Gets the value of the padChar property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPadChar() {
        return padChar;
    }

    /**
     * Sets the value of the padChar property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPadChar(String value) {
        this.padChar = value;
    }

    /**
     * Gets the value of the padDir property.
     * 
     * @return
     *     possible object is
     *     {@link PadDirectionList }
     *     
     */
    public PadDirectionList getPadDir() {
        return padDir;
    }

    /**
     * Sets the value of the padDir property.
     * 
     * @param value
     *     allowed object is
     *     {@link PadDirectionList }
     *     
     */
    public void setPadDir(PadDirectionList value) {
        this.padDir = value;
    }

    /**
     * Gets the value of the decimalMinimum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDecimalMinimum() {
        return decimalMinimum;
    }

    /**
     * Sets the value of the decimalMinimum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDecimalMinimum(String value) {
        this.decimalMinimum = value;
    }

    /**
     * Gets the value of the decimalMaximum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDecimalMaximum() {
        return decimalMaximum;
    }

    /**
     * Sets the value of the decimalMaximum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDecimalMaximum(String value) {
        this.decimalMaximum = value;
    }

    /**
     * Gets the value of the length property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getLength() {
        return length;
    }

    /**
     * Sets the value of the length property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setLength(BigInteger value) {
        this.length = value;
    }

}
