//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.03.10 at 10:55:55 AM EDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "urn:epcglobal:tdt:xsd:1")
package org.epcglobalinc;
