//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.03.10 at 10:55:55 AM EDT 
//


package org.epcglobalinc;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SchemeNameList.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="SchemeNameList">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="SGTIN-64"/>
 *     &lt;enumeration value="SGTIN-96"/>
 *     &lt;enumeration value="SGLN-64"/>
 *     &lt;enumeration value="SGLN-96"/>
 *     &lt;enumeration value="GRAI-64"/>
 *     &lt;enumeration value="GRAI-96"/>
 *     &lt;enumeration value="GIAI-64"/>
 *     &lt;enumeration value="GIAI-96"/>
 *     &lt;enumeration value="SSCC-64"/>
 *     &lt;enumeration value="SSCC-96"/>
 *     &lt;enumeration value="GID-96"/>
 *     &lt;enumeration value="USDOD-64"/>
 *     &lt;enumeration value="USDOD-96"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "SchemeNameList")
@XmlEnum
public enum SchemeNameList {

    @XmlEnumValue("SGTIN-64")
    SGTIN_64("SGTIN-64"),
    @XmlEnumValue("SGTIN-96")
    SGTIN_96("SGTIN-96"),
    @XmlEnumValue("SGLN-64")
    SGLN_64("SGLN-64"),
    @XmlEnumValue("SGLN-96")
    SGLN_96("SGLN-96"),
    @XmlEnumValue("GRAI-64")
    GRAI_64("GRAI-64"),
    @XmlEnumValue("GRAI-96")
    GRAI_96("GRAI-96"),
    @XmlEnumValue("GIAI-64")
    GIAI_64("GIAI-64"),
    @XmlEnumValue("GIAI-96")
    GIAI_96("GIAI-96"),
    @XmlEnumValue("SSCC-64")
    SSCC_64("SSCC-64"),
    @XmlEnumValue("SSCC-96")
    SSCC_96("SSCC-96"),
    @XmlEnumValue("GID-96")
    GID_96("GID-96"),
    @XmlEnumValue("USDOD-64")
    USDOD_64("USDOD-64"),
    @XmlEnumValue("USDOD-96")
    USDOD_96("USDOD-96");
    private final String value;

    SchemeNameList(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static SchemeNameList fromValue(String v) {
        for (SchemeNameList c: SchemeNameList.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
